---
- name: SHLiC Controller
  hosts: localhost
  become: true
  become_method: sudo

  tasks:
    - name: Set the timezone
      file:
        src: /usr/share/zoneinfo/America/New_York
        dest: /etc/localtime
        state: link

    - name: Update package repo
      apt: update_cache=yes
    - name: Upgrade all instaled packages
      apt: upgrade=dist

    - name: Disable bluetooth LE services
      systemd:
        name: bluetooth
        enabled: no
        state: stopped

    - name: Install gunicorn
      apt:
        name: gunicorn
        state: present

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Site configuration in nginx
      blockinfile:
        dest: /etc/nginx/sites-available/shlic-controller
        create: yes
        state: present
        block: |
          server {
            listen 8080;
            server_name _;
            location / {
              include proxy_params;
              proxy_pass http://unix:/home/pi/SHLiC/shlic-controller.sock;
            }
          }

    - name: Link in the site configuration
      file:
        src: /etc/nginx/sites-available/shlic-controller
        dest: /etc/nginx/sites-enabled/shlic-controller
        state: link

    - name: Install memcached
      apt:
        name: memcached
        state: present

    - name: Install python-gpiozero
      apt:
        name: python-gpiozero
        state: present

    - name: Install pip
      apt: 
        name: python-pip
        state: present

    - name: Install pymemcache via pip
      command: /usr/bin/pip install pymemcache

    - name: Install requests via pip
      command: /usr/bin/pip install requests

    - name: Install Flask via pip
      command: /usr/bin/pip install flask

    - name: Install shlic service configuration file
      blockinfile:
        dest: /etc/systemd/system/shlic-controller.service
        create: yes
        state: present
        block: |
          [Unit]
          Description=gunicorn for shlic-controller
          After=network.target
          Requires=network.target
          [Service]
          User=pi
          Group=pi
          WorkingDirectory=/home/pi/SHLiC
          Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"
          ExecStart=/usr/bin/gunicorn --workers 3 --bind unix:/home/pi/SHLiC/shlic-controller.sock -m 000 runController:controller.engine.app
          [Install]
          WantedBy=multi-user.target

    - name: Enable SHLiC-controller service
      systemd:
        name: shlic-controller
        enabled: yes
        state: stopped

    - name: chmod the watchdog script
      file:
        path: /home/pi/SHLiC/bin/shlic-controllerwatchdog.sh
        mode: 0755
        state: file

    - name: Put the watchdog script into crontab
      blockinfile:
        dest: /etc/crontab
        create: yes
        state: present
        block: |
          * * * * * root /home/pi/SHLiC/bin/shlic-controllerwatchdog.sh

    - debug: msg="You can now configure shlic-controller.cfg as needed.  Once done, reboot."